# Generated by Django 4.2.7 on 2024-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
